### ISSUE TITLE
bug with comments

### ISSUE THREAD

**Issue by alessioalex** [jotform/css.js#4]
Try to parse this:

``` css
.someSelector 
{ 
  margin:40px 10px; 
  padding:5px; /* This is { blue } */
}
```

You will get this:

``` css
[
  {
    "selector": ".someSelector",
    "rules": [
      {
        "directive": "margin",
        "value": "40px 10px"
      },
      {
        "directive": "padding",
        "value": "5px"
      },
      {
        "directive": "",
        "value": "/* This is { blue",
        "defective": true
      }
    ]
  }
]
```

Similar to https://github.com/reworkcss/css/issues/24
